name: python-test-valet
on:
  workflow_dispatch:
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: echo message
      run: echo Hello World
